### ISSUE TITLE
USER STORY: Authentication

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#10]
As a **user** I can **create a new account** so that **I can start logging sessions**

### Acceptance Criteria 
- Acceptance Criteria 1 - sign up form appears
- Acceptance Criteria 2 - add name and password with input validation
- Acceptance Criteria 3 - success message appears on sign up completion

### Tasks
- [x] Task 1 - install allauth module
- [x] Task 2 - set up the sign up form/view
- [x] Task 3 - set up success message
