### ISSUE TITLE
USER STORY: Templates

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#11]
As a **user** I can **see the webpage** so that **interact navigate to sign up/sign in pages**

### Acceptance Criteria 
- Acceptance Criteria 1 - basic html is rendered on the page, no styling yet
- Acceptance Criteria 2 - buttons/links to sign up/sign in/sign out are visible + functioning
- Acceptance Criteria 3 - the signed out/unregistered user is redirected to the index page

### Tasks
- [x] Task 1 - set up index view
- [x] Task 2 - set up base template
- [x] Task 3 - set up index template + url
