### ISSUE TITLE
USER STORY: Sign up/in redirect

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#12]
As a **user** I can **sign up/in** so that **see 'My sessions' page**

### Acceptance Criteria 
- Acceptance Criteria 1 - user is redirected to a page listing their logged sessions
- Acceptance Criteria 2 - this page is only accessible to authenticated users
- Acceptance Criteria 3

### Tasks
- [x] Task 1 - set up view for my sessions list
- [x] Task 2 - set up template for my sessions
- [x] Task 3 - link up urls for my sessions
