### ISSUE TITLE
USER STORY: Create sessions

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#13]
As a **registered user** I can **log a new training session record** so that **keep track of my training sessions**

### Acceptance Criteria 
- Acceptance Criteria 1 - Button to 'add session' functions
- Acceptance Criteria 2 - User directed to add session form
- Acceptance Criteria 3 - On save, session is logged and displayed in session list

### Tasks
- [x] Task 1 - create view code for add session
- [x] Task 2 - Build 'add session' form page template + link url
- [x] Task 3 - link add session button to the form page
