### ISSUE TITLE
USER STORY: View sessions

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#14]
As a **registered user** I can **see a list of my sessions** so that **I can click on one and view the session detail**

### Acceptance Criteria 
- Acceptance Criteria 1 - my-sessions page displays a list of user's logged sessions
- Acceptance Criteria 2 - each list item is clickable and takes the user to the session detail page
- Acceptance Criteria 3

### Tasks
- [x] Task 1 - Fix for loop to loop through the user's sessions
- [x] Task 2 - Fix table to display the sessions
- [x] Task 3 - Make each session on list a link to the sesssion detail page
