### ISSUE TITLE
USER STORY: Update Session

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#16]
As a **user** I can **click on edit button** so that **I can update the content of a logged session**

### Acceptance Criteria 
- Acceptance Criteria 1 - edit button links to the update session page
- Acceptance Criteria 2 - update session page displays the session form
- Acceptance Criteria 3 - any edits that are made are stored in the database

### Tasks
- [x] Task 1 - create update session form
- [x] Task 2 - create update session view, template + link the url
- [x] Task 3 - link the edit button on the list of sessions page to the edit session page
