### ISSUE TITLE
USER STORY: Delete session

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#17]
As a **user** I can **click on delete button** so that **I can delete the record of a logged session**

### Acceptance Criteria 
- Acceptance Criteria 1 - delete button links to the delete session confirmation page
- Acceptance Criteria 2 - delete session page has buttons to confirm deletion or to return to list of sessions page
- Acceptance Criteria 3 - database is updated accordingly

### Tasks
- [x] Task 1 - create delete session view, template + link the url
- [x] Task 2 - link the delete button on the list of sessions page to the delete session confirmation page
- [x] Task 3 - create deletion success message and revert user back to list of sessions page
