### ISSUE TITLE
USER STORY: Fonts + colours + images

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#18]
As a **user** I can **access a coherently designed site** so that **I can have a positive emotional experience while using the site**

### Acceptance Criteria 
- Acceptance Criteria 1 - each page of the site follows a cohesive design
- Acceptance Criteria 2 - colours are contrast sufficently for user friendly experience
- Acceptance Criteria 3 - fonts and images aren't distracting

### Tasks
- [x] Task 1 - choose fonts for the title/content
- [x] Task 2 - choose a colour scheme for the site, implement across all pages
- [x] Task 3 - source images from open-source websites
