### ISSUE TITLE
USER STORY: Customize Django default pages

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#20]
As a **user** I can **access the sign up/in/out pages** and have **a positive emotional experience**

### Acceptance Criteria 
- Acceptance Criteria 1 - the default pages follow the design concept of the site
- Acceptance Criteria 2 - the forms and buttons are easy to use without excess text and content on the page
- Acceptance Criteria 3 - 

### Tasks
- [x] Task 1 - import the django account files to the local ide
- [x] Task 2 - extend the pages from the base template
- [x] Task 3 - edit the content and check forms/buttons function
