### ISSUE TITLE
USER STORY: Styling session log pages

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#21]
As a **user** I can **access the session log pages** and **see a consistent colour scheme and design stylee**

### Acceptance Criteria 
- Acceptance Criteria 1 - create session page looks good
- Acceptance Criteria 2 - edit session page looks good
- Acceptance Criteria 3 - delete session page looks good

### Tasks
- [x] Task 1 - apply styling to create session page
- [x] Task 2 - apply styling to edit session page
- [x] Task 3 - apply styling to delete session page
