### ISSUE TITLE
USER STORY: Error pages

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#22]
As a **user** I can **see an error message** if **I am redirected to an error page**

### Acceptance Criteria 
- Acceptance Criteria 1 - the page follows the general colourscheme and styling of the site
- Acceptance Criteria 2 - the message is clearly displayed
- Acceptance Criteria 3 - there is a button for users to click to return the home page

### Tasks
- [x] Task 1 - create 403, 404, 405, 500.html pages
- [x] Task 2 - extend pages from base.html
- [x] Task 3 - add a link in a button to return the user to the home page
