### ISSUE TITLE
USER STORY: Bug fixes

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#23]
As a **developer** I can **fix any bugs that appear on the site** so that **it can be deployed succesfully**

### Acceptance Criteria 
- Acceptance Criteria 1 - all buttons work correctly
- Acceptance Criteria 2 - all forms work correctly
- Acceptance Criteria 3 - all links work correctly

### Tasks
- [x] Task 1 - disable the submit button onclick so duplicates aren't made
- [x] Task 2 - test that data submitted in the forms is logged in the db
- [x] Task 3 - test that external links all open in a new window
