### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#24]
As a **user** I can **navigate to the About page** so that **I can learn more about the app**

### Acceptance Criteria 
- Acceptance Criteria 1 - link appears in nav bar
- Acceptance Criteria 2 - information about the app is displayed following the style of the site
- Acceptance Criteria 3 - link to get started will link user to the sign up page

### Tasks
- [x] Task 1 - create view, template, link url for the About page
- [x] Task 2 - create content about how the app works and who it's for
- [x] Task 3 - add a button to link to the sign up page
