### ISSUE TITLE
USER STORY: Location Suggestion Box

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#27]
As a **user** I can **submit a location suggestion to the owner of the website** so that **they can review my suggestion and add it to the map**

### Acceptance Criteria 
- Acceptance Criteria 1 - suggestion input box and button is visible on the page below the map
- Acceptance Criteria 2 - suggestion is submitted to a database that only the admin can see, modify
- Acceptance Criteria 3 

### Tasks
- [ ] Task 1 - create model for suggestions
- [ ] Task 2 - create form for suggestions
- [ ] Task 3 - create view, display form on Locations page
