### ISSUE TITLE
USER STORY: Favicon

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#28]
As a **programmer** I need to **add a favicon to the site** so that **the UX is improved**

### Acceptance Criteria 
- Acceptance Criteria 1 - favicon is visible in the user's brower tab
- Acceptance Criteria 2
- Acceptance Criteria 3

### Tasks
- [x] Task 1 - create favicon
- [x] Task 2 - add image to project file
- [x] Task 3 - load in head of base.html
