### ISSUE TITLE
USER STORY: Python Automated Testing

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#29]
As a **developer** I can **create tests for the python files** so that **I can make sure the app functions correctly**

### Acceptance Criteria 
- Acceptance Criteria 1 - test file for each python file exists
- Acceptance Criteria 2 - tests for classes/fuctions/methods are carried out
- Acceptance Criteria 3 - results are recorded in the README

### Tasks
- [ ] Task 1 - create test files
- [ ] Task 2 - carry out tests
- [ ] Task 3 - fix any issues arising from the tests
- [ ] Task 4 - record results in the README
