### ISSUE TITLE
USER STORY: Manual Testing

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#30]
As a **developer** I can **perform manual testing** so that **I can ensure the app works well**

### Acceptance Criteria 
- Acceptance Criteria 1 - sign up/in/out work correctly
- Acceptance Criteria 2 - CRUD functionality works correctly
- Acceptance Criteria 3 - results are recorded in the README

### Tasks
- [x] Task 1 - test sign up/in/out forms and buttons
- [x] Task 2 - test session log creae/read/update/delete forms
- [x] Task 3 - record results in the README
