### ISSUE TITLE
USER STORY: Code Validation and Accessibility Testing

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#31]
As a **developer** I can **test the app and code base using 3rd party testing apps** so that **I can ensure the app is adhering to best practice standards and is fully accessible to all users**

### Acceptance Criteria 
- Acceptance Criteria 1 - code base is tested with W3C Markup Validation, W3C jigsaw, PEP 8
- Acceptance Criteria 2 - app is tested with WAVE for accessibility
- Acceptance Criteria 3 - app is tested with Lighthouse for Performance rating

### Tasks
- [x] Task 1 - test code base, html pages
- [x] Task 2 - make any neccessary changes to optimize the results
- [x] Task 3 - record results and improvements in the README
