### ISSUE TITLE
USER STORY: Create Session Model

### ISSUE THREAD

**Issue by barty-s** [barty-s/windsurf-session-log#9]
As a **developer** I can **see the session model** so that **I can add it to the Django admin page**

### Acceptance Criteria 
- Acceptance Criteria 1 - the model is added to models.py
- Acceptance Criteria 2 - the model is migrated to the db
- Acceptance Criteria 3  

### Tasks
- [x] Task 1 - create model in models.py in the session app
- [x] Task 2 - migrate the changes
- [x] Task 3 - access the model in the admin page

**Comment by VidyaYadavv1519** [comment]
hiiii, i want to do this issue,
can you please assign me ??

**Comment by barty-s** [comment]
This is not an open source project
